### ISSUE TITLE
Dev instruction problems

### ISSUE THREAD

**Issue by jankatins** [jupyter-xeus/xeus-sql#12] opened 2020-12-30 21:56 UTC
Running the requested lines to setup a dev environment (https://github.com/jupyter-xeus/xeus-sql/blob/master/CONTRIBUTING.md) on a mac osx install (with micromamba instead of conda/mamba) results in this:

```
~/external/xeus-sql/build on master (conda:xeus-sql)
[22:14:01] λ  cmake -D CMAKE_INSTALL_PREFIX=$CONDA_PREFIX ..
-- Building xeus-sql v0.0.3
-- Found nlohmann_json: /Users/jan.katins/.local/micromamba/envs/xeus-sql/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found suitable version "3.9.1", minimum required is "3.2.0")
-- Found nlohmann_json: /Users/jan.katins/.local/micromamba/envs/xeus-sql/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found suitable version "3.9.1", minimum required is "3.7.3")
-- Soci found: Looking for plugins
--     * Plugin mysql not found.
--     * Plugin odbc not found.
--     * Plugin postgresql not found.
--     * Plugin sqlite3 found /Users/jan.katins/.local/micromamba/envs/xeus-sql/lib/libsoci_sqlite3.dylib.
CMake Error at CMakeLists.txt:141 (message):
  Unsupported compiler -- xeus-sql requires C++14 support!
Call Stack (most recent call first):
  CMakeLists.txt:198 (xsql_set_common_options)
  CMakeLists.txt:239 (xsql_create_target)


-- Configuring incomplete, errors occurred!
See also "/Users/jan.katins/external/xeus-sql/build/CMakeFiles/CMakeOutput.log".
See also "/Users/jan.katins/external/xeus-sql/build/CMakeFiles/CMakeError.log".
```

I tried to work around that check (assuming my clang supports c++14) by 

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 09bc890..0738e8a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -134,12 +134,7 @@ macro(xsql_set_common_options target_name)
         endif ()

         # C++14 flag
-        CHECK_CXX_COMPILER_FLAG("-std=c++14" HAS_CPP14_FLAG)
-        if (HAS_CPP14_FLAG)
-            target_compile_features(${target_name} PRIVATE cxx_std_14)
-        else ()
-            message(FATAL_ERROR "Unsupported compiler -- xeus-sql requires C++14 support!")
-        endif ()
+        target_compile_features(${target_name} PRIVATE cxx_std_14)

         # Enable link time optimization and set the default symbol
         # visibility to hidden (very important to obtain small binaries)
```

But this failed then in `make`:
```
...
Scanning dependencies of target xeus-sql
[ 50%] Building CXX object CMakeFiles/xeus-sql.dir/src/xeus_sql_interpreter.cpp.o
In file included from /Users/jan.katins/external/xeus-sql/src/xeus_sql_interpreter.cpp:24:
/Users/jan.katins/external/xeus-sql/include/xeus-sql/soci_handler.hpp:31:27: warning: comparison of integers of different signs: 'int' and 'std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>::size_type' (aka 'unsigned long') [-Wsign-compare]
        for (int i = 2; i < tokenized_input.size(); i++)
                        ~ ^ ~~~~~~~~~~~~~~~~~~~~~~
/Users/jan.katins/external/xeus-sql/src/xeus_sql_interpreter.cpp:70:24: warning: enumeration values 'dt_blob' and 'dt_xml' not handled in switch [-Wswitch]
                switch(props.get_data_type())
                       ^
2 warnings generated.
[ 66%] Linking CXX shared library libxeus-sql.dylib
ld: warning: -pie being ignored. It is only used when linking a main executable
[ 66%] Built target xeus-sql
Scanning dependencies of target xsql
[ 83%] Building CXX object CMakeFiles/xsql.dir/src/main.cpp.o
[100%] Linking CXX executable xsql
ld: unknown option: --disable-new-dtags
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [xsql] Error 1
make[1]: *** [CMakeFiles/xsql.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jankatins** [comment] 2020-12-30 22:26
Ok, got it running: by also removing the `--disable-new-dtags` flag:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 09bc890..e703ac9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -116,7 +116,7 @@ set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib:${CMAKE_INSTALL_PREFIX}/${C
 # E.g. without this option libpq fails to be loaded by libsoci_postgresql, which is loaded
 # by libsoci_core, which is loaded by us.
 # source: https://github.com/chenxiaolong/DualBootPatcher/pull/548
-set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--disable-new-dtags")
+set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl")
```

I copied the kernel spec to my virtualenv which hosts my jupyter lab, restarted, created a kernel and with `%LOAD postgresql dbname=bi_dwh` I got it running, nice :-) 

(Now running into the problem that the soci sessions seems to error because it does not understand postgresql ENUM data types, but thats a different problem :-))

**Comment by marimeireles** [comment] 2020-12-31 10:44
Regarding the C++14 error, are you running this on an OSX?
And thanks for the fix, will try it right away in our CI :) haven't thought about it

> But this failed then in make:

I don't think this was the problem because it only showed a few warnings... I'll fix it now.
If you can reproduce the problem again I'd be interested in the complete log, please.

Hum!
> (Now running into the problem that the soci sessions seems to error because it does not understand postgresql ENUM data types, but thats a different problem :-))

Could you paste the error here? Or in a new issue?
I encountered a problem with NULL types while doing some tests before, but I didn't fix it yet. It doesn't seem to be a problem with my side, but with SOCI. I'll probably open an issue there.

Thanks for testing so early! :)
Out of curiosity, how did you find out about the project?

**Comment by marimeireles** [comment] 2020-12-31 11:42
I just saw the error with the types now.
It's only happening in clang, apparently. Thanks for the catch! Will also have a look on them now =)

**Comment by marimeireles** [comment] 2020-12-31 13:26
Actually it's just a warning, not super straightforward to fix it, will open an issue for it, thanks again for opening the issue
The OSX issue was fixed by #10 
Soon we should have a conda-forge package =)

**Closed by marimeireles** 2020-12-31 13:26 UTC

**Comment by jankatins** [comment] 2020-12-31 19:11
Error re ENUM: 

```
Error: unknown data type with typelem: 26976010 for colNum: 36 with name: yyyy_column while executing "select * from os_dim.xxxx limit 10".
```

The table contains a column which is an ENUM, similar to this (untested): 

```SQL
CREATE TYPE public.enum_name AS ENUM ('aaaa','bbbb');
CREATE TABLE public.test AS (
SELECT 
'aaaa' :: public.enum_name as enum_col,
1 as int_col,
'blabla' as text_col
);
```

It also seems that there is still something wrong, I don't get any output, only the column names:

![image](https://user-images.githubusercontent.com/890156/103422810-9070dc00-4ba3-11eb-90ae-17fbcbb7a8c7.png)

> Out of curiosity, how did you find out about the project?

I searched for SQL notebook, saw the sqlite kernel, followed it to github and snooped around... More or less on a hunch of "if there is a sqlite kernel, why not a generic sql kernel"... :-)

(my dream: a kernel for each database I have access to as defined in my jetbrains editor, so I don't have to remember to delete the connection string/PW in the notebook before converting to html/pdf)

**Comment by jankatins** [comment] 2020-12-31 19:25
Seems soci is also not able to take arrays: https://github.com/SOCI/soci/issues/776 :-(

**Comment by marimeireles** [comment] 2020-12-31 19:56
> It also seems that there is still something wrong, I don't get any output, only the column names:

Isn't it right? It should show one value, `bla` because you asked for 1?

> (my dream: a kernel for each database I have access to as defined in my jetbrains editor, so I don't have to remember to delete the connection string/PW in the notebook before converting to html/pdf)

Hmmm idk how your environment works, but if you make different environments, you can have different SOCI implementations. You know? Like one with postgres, another with SQLite...

>I searched for SQL notebook, saw the sqlite kernel, followed it to github and snooped around... More or less on a hunch of "if there is a sqlite kernel, why not a generic sql kernel"... :-)

hehe awesome! :)

**Comment by jankatins** [comment] 2020-12-31 20:33
`Select 1 as bla` should give a table:

```
+---+
|bla|
+---+
|1  |
+---+
```

> Hmmm idk how your environment works, but if you make different environments, you can have different SOCI implementations. You know? Like one with postgres, another with SQLite...

I have like 5 different postgresql DBs I want to connect to :-) So it's more about to pass in the connection string in the kernel config instead of writing it in the first line. E.g. I'm still using https://github.com/Cadair/jupyter_environment_kernels for my virtualenvs and I can imagine adding something similar to add multiple DB connection kernels... Or some script to generate kernel configs in the virtualenv which hosts my jupyter lab :-)
